// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHgCkq8O4Imtr2onB_CVmJSbqgxpmK6WE',
    appId: '1:47534420888:web:d9751cdc7a26e2e8c571ed',
    messagingSenderId: '47534420888',
    projectId: 'akademif35',
    authDomain: 'akademif35.firebaseapp.com',
    storageBucket: 'akademif35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMl2OdV6zb2I3GD6UU06s-r34JmhSwzpM',
    appId: '1:47534420888:android:8ef6e549f9299228c571ed',
    messagingSenderId: '47534420888',
    projectId: 'akademif35',
    storageBucket: 'akademif35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQgNiXuiXI9TvRALvTD_C67_sEEGUFsBA',
    appId: '1:47534420888:ios:1d34977ab5ffe139c571ed',
    messagingSenderId: '47534420888',
    projectId: 'akademif35',
    storageBucket: 'akademif35.appspot.com',
    iosClientId: '47534420888-jjd7d1u5d79a681nfucct7j3bh8cf1pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.f35',
  );
}
